name: Update README with Latest Hashnode Post

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch latest blog post
        run: |
          # Fetch the latest post from Hashnode API
          response=$(curl -s "https://api.hashnode.com/v1/posts?page=1&perPage=1")

          # Debugging: Print the API response
          echo "Hashnode API Response: $response"

          # Extract the latest post title and URL (Assuming the response includes a URL)
          post_title=$(echo "$response" | jq -r '.posts[0].title')
          post_url="https://hashnode.com/@harrypage" # Adjust this if the API provides a specific post URL

          # Ensure the title is not empty
          if [ -z "$post_title" ] || [ "$post_title" == "null" ]; then
            echo "Error: No valid latest post found!"
            exit 1
          fi

          # Format the post
          post="🔗 [$post_title]($post_url)"

          # Debugging: Print extracted post
          echo "Latest Post: $post"

          # Save the latest post to a file
          echo "$post" > latest_post.md

      - name: Check latest_post.md
        run: |
          # Print the content of latest_post.md
          cat latest_post.md
          
          # Ensure latest_post.md is not empty
          if [ ! -s latest_post.md ]; then
            echo "Error: latest_post.md is empty!"
            exit 1
          fi

      - name: Update README
        run: |
          # Read latest post from file
          post=$(cat latest_post.md)

          # Ensure post content is valid before updating README
          if [ -z "$post" ]; then
            echo "Error: No latest post found, skipping README update."
            exit 1
          fi

          # Replace content inside <!-- BLOG-POST-LIST:START --> and <!-- BLOG-POST-LIST:END -->
          sed -i "/<!-- BLOG-POST-LIST:START -->/,/<!-- BLOG-POST-LIST:END -->/c\<!-- BLOG-POST-LIST:START -->\n$post\n<!-- BLOG-POST-LIST:END -->" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated latest Hashnode post" || exit 0
          git push
