name: Update blog posts
on:
  schedule:
    - cron: "0 * * * *" # mỗi giờ
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://holydev.uk/rss.xml"