name: "📚 Latest Blog Update"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Runs every hour, on the hour

jobs:
  update_blogs:
    name: "Update With Latest Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚 Fetch Latest Hashnode Posts"
        run: |
          RESPONSE=$(curl -s -X POST https://gql.hashnode.com \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.HASHNODE_PAT }}" \
            --data '{"query":"{ user(username: \"harrypage\") { publications(first: 1) { edges { node { title, posts(first: 5) { edges { node { title, url } } } } } } } }"}')
          echo "Hashnode API Response: $RESPONSE"
          BLOG_POSTS=$(echo "$RESPONSE" | jq -r '.data.user.publications.edges[0].node.posts.edges[] | "🔗 [" + .node.title + "]( " + .node.url + " )"')
          echo "$BLOG_POSTS" > latest_blogs.md

      - name: "📄 Update README with Latest Blogs"
        run: |
          sed -i '/<!-- BLOG-POST-LIST:START -->/,/<!-- BLOG-POST-LIST:END -->/c\<!-- BLOG-POST-LIST:START -->\n'$BLOG_POSTS'\n<!-- BLOG-POST-LIST:END -->' README.md

      - name: "📤 Commit and Push Changes"
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated latest blog posts from Hashnode"
          git push
