name: Update README with Latest Hashnode Post

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch latest blog post
        run: |
          curl -X POST https://api.hashnode.com/ \
          -H "Content-Type: application/json" \
          --data '{ "query": "{ user(username: \"harrypage\") { publication { posts(page: 0) { title, url } } } }" }' \
          | jq -r '.data.user.publication.posts[0] | "🔗 [" + .title + "](" + .url + ")"' > latest_post.md

      - name: Update README
        run: |
          # Debug: Show latest post content
          cat latest_post.md
          
          # Store latest post in a variable
          post=$(cat latest_post.md)

          # Check if latest_post.md is empty
          if [ -z "$post" ]; then
            echo "Error: latest_post.md is empty!"
            exit 1
          fi

          # Replace the latest post section in README.md
          sed -i "/<!-- BLOG-POST-LIST:START -->/,/<!-- BLOG-POST-LIST:END -->/c\<!-- BLOG-POST-LIST:START -->\n$post\n<!-- BLOG-POST-LIST:END -->" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated latest Hashnode post" || exit 0
          git push
